#this is necessary for Linux to even register that the GPS is connected
#if this kernel module isnt loaded, the port that the garmin is connected
#to will NOT register (no /dev/ttyUSB# will be created)
#This can probably be permanently loaded, but IDK how yet (5-8-19)
sudo modprobe garmin_gps
while :
do
        echo "Refreshing GPS"
	#grab most recent coordinate and replace GPS.txt with it
	tail --lines=4 /home/umigv/catkin_ws/GPS.txt > /home/umigv/catkin_ws/GPS.txt
	#convert coordinates for 3 seconds
	#this script (except for 'timeout 3s') was generated by gebabbel (installed on this NUC)
	timeout 3s gpsbabel -T -i garmin -f /dev/ttyUSB1 -o nmea,gpgga=1,gpvtg=1 -F /home/umigv/catkin_ws/GPS.txt
done

